action: added backend & db smoke test and frontend test

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -65,6 +65,9 @@ jobs:
             sudo usermod -aG docker $USER
             newgrp docker
 
+            echo "Install JQ for JSON processing"
+            sudo apt-get install -y jq
+
             echo "Installing Docker Compose..."
             sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
             sudo chmod +x /usr/local/bin/docker-compose
@@ -79,8 +82,20 @@ jobs:
 
       - name: Smoke Test
         run: |
-          sleep 60  # Wait for the services to be up and running
-          curl http://$EC2_PUBLIC_IP:8800/books
+          sleep 30  # Wait 30s for the services to be ready
+          # curl http://$EC2_PUBLIC_IP:8800/books
+          echo "💥 Fetch the books data from the API and check if there are exactly 3 books..."
+          DATA=$(curl -s http://$EC2_PUBLIC_IP:8800/books)
+          COUNT=$(echo $DATA | jq '. | length')
+          if [ "$COUNT" -eq 3 ]; then
+            echo "✅ Smoke Test - backend & db passed: Correct number of books returned."
+          else
+            echo "❌ Smoke Test - backend & db test failed: Incorrect number of books returned."
+            echo "Received data: $DATA"
+            exit 1  # This will fail the workflow if the test does not pass
+          fi
+
+          echo "💥 Smoke Test - frontend test: should return frontend code"
           curl http://$EC2_PUBLIC_IP:5173
 
       - name: Cleanup
