added: pull latest images from ecr to qa ec2 machine

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -186,7 +186,59 @@ jobs:
       #     aws ecr list-images --repository-name cs686-midterm-backend --region us-east-1
       #     aws ecr list-images --repository-name cs686-midterm-frontend --region us-east-1
 
+      - name: SSH Connect to QA and Pull Latest Image and Deploy
+        run: |
+          ssh -i ~/.ssh/id_rsa ec2-user@${{ env.EC2_PUBLIC_IP }} << 'EOF'
+            set -e  # Exit on error
+            echo "SSH connection successful!"
 
+            echo "🔍 Checking AWS CLI installation..."
+            if ! command -v aws &> /dev/null; then
+              echo "Installing AWS CLI..."
+
+              if ! command -v unzip &> /dev/null; then
+                echo "Installing unzip..."
+                sudo yum update -y
+                sudo yum install -y unzip
+              fi
+
+              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+              unzip awscliv2.zip
+              sudo ./aws/install
+              rm -rf awscliv2.zip aws
+            else
+              echo "✅ AWS CLI already installed."
+            fi
+
+            echo "AWS CLI Version:"
+            aws --version || echo "❌ AWS CLI installation failed!"
+
+            echo "Configuring AWS Credentials..."
+            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
+            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
+            export AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }}
+            export AWS_DEFAULT_REGION=${{ env.AWS_REGION }}
+            export AWS_REGION=${{ env.AWS_REGION }}
+
+            echo "Logging in to AWS ECR..."
+            aws ecr get-login-password --region ${{ env.AWS_REGION }} | sudo docker login --username AWS --password-stdin ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com || {
+              echo "❌ AWS ECR login failed!"
+              exit 1
+            }
+
+            echo "Pulling latest Docker images from ECR..."
+            sudo docker pull ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/cs686-midterm-backend:latest
+            sudo docker pull ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/cs686-midterm-frontend:latest
+
+            # sudo docker run -d -p 5173:5173 ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/frontend-image:latest
+            # sudo docker run -d -p 8800:8800 \
+            # -e DB_HOST='jobboard-mysql.cnvfcs4t89vv.us-east-1.rds.amazonaws.com' \
+            # -e DB_USER='admin' \
+            # -e DB_PASS='CS686password' \
+            # -e DB_NAME='test' \
+            # -e PORT=8800 \
+            # 746488717346.dkr.ecr.us-east-1.amazonaws.com/backend-image:latest
+            
       - name: Cleanup
         if: always()
         run: |
